set relativenumber
set incsearch
set timeoutlen=200
set backspace=indent,eol,start
set history=1000
set hlsearch	
set autoindent
set background=dark
set cursorline
set expandtab
set foldlevel=99
set foldmethod=indent
set laststatus=2
set linebreak
set noerrorbells
set number
set scrolloff=5
set shiftround
set shiftwidth=4
set sidescrolloff=5
set smartcase
set tabstop=4
set title
syntax on
