set autoindent
set background=dark
set backspace=indent,eol,start
set cursorline
set expandtab
set foldlevel=99
set foldmethod=indent
set history=1000
set hlsearch	
set incsearch
set laststatus=2
set linebreak
set noerrorbells
set number
set relativenumber
set scrolloff=5
set shiftround
set shiftwidth=4
set sidescrolloff=5
set smartcase
set tabstop=4
set textwidth=72
set timeoutlen=200
set title
syntax on
